### ISSUE TITLE
Subject not correct: =?iso-8859-7?Q?..........

### ISSUE THREAD

**Issue by DarkAllMan** [tedious/Fetch#142]
Some of my received mails contain =?iso-8859-7?Q? in the subject. How can I resolve this?

**Comment by DarkAllMan** [comment]
I think the solution is:
http://www.php.net/manual/en/function.imap-utf8.php#102081

So it needs to be added to the decoding of the subject and addresses decoding

**Comment by aguzmans** [comment]
I had the same issue and fixed it the same way. It worked for me.

**Comment by DarkAllMan** [comment]
Sometimes the From address has the same... still need to figure out where to implement this for the from address.

**Comment by aguzmans** [comment]
I've used it for the subjects only. I had a list of 2 mails and 3 of them had this issue, but I just filtered everything. I do not have any issues with the addresses, maybe due to. This is what I use to get the sender:

$messages = $this->server->getMessages();
foreach ($messages as $key => $message) {
    $sender = $message->getAddresses('from')["address"]; 
.
.
.
}
Maybe you can try to filter here: $message->getAddresses('from')["address"];

**Comment by tedivm** [comment]
Character encoding has been updated with the current release. I'm asking that people submit new tickets for any bugs that they find.
